# Generated by Django 2.2.4 on 2019-09-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, null=True, verbose_name='クラン名')),
                ('founded_date', models.DateField(verbose_name='設立日')),
                ('image', models.ImageField(default=None, upload_to='clan_photos', verbose_name='サムネ画像')),
                ('point', models.IntegerField(default=0, verbose_name='ポイント')),
            ],
        ),
    ]
