# Generated by Django 2.2.6 on 2019-10-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='hobby',
            field=models.CharField(blank=True, help_text='半角スペースで単語わけしてください', max_length=255, null=True, verbose_name='趣味'),
        ),
        migrations.AddField(
            model_name='clan',
            name='introduction',
            field=models.TextField(default=None, max_length=2000, verbose_name='紹介'),
        ),
    ]
