# Generated by Django 2.2.6 on 2019-10-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191019_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(default=None, max_length=2000, null=True, verbose_name='紹介'),
        ),
    ]
