# Generated by Django 2.2.4 on 2019-09-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190911_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='event',
        ),
    ]
