# Generated by Django 2.2.6 on 2019-10-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_auto_20191019_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follow_user_email',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follow_user_hobby',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follow_user_name',
        ),
    ]
