# Generated by Django 2.2.4 on 2019-09-11 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participant',
        ),
        migrations.AddField(
            model_name='event',
            name='participant',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
