# Generated by Django 2.2.6 on 2019-10-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('held_at', models.DateTimeField(default=None)),
                ('hobby', models.CharField(blank=True, help_text='半角スペースで単語わけしてください', max_length=255, null=True, verbose_name='趣味')),
                ('image', models.ImageField(default=None, upload_to='photos', verbose_name='サムネ画像')),
                ('member_capacity', models.IntegerField(default=None)),
                ('leader', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('place', models.CharField(default=None, max_length=255)),
                ('address', models.CharField(default=None, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, default=None, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, default=None, max_digits=9)),
                ('introduction', models.TextField(default=None, max_length=2000, verbose_name='紹介')),
            ],
        ),
    ]
