# Generated by Django 2.2.4 on 2019-09-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190911_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participant',
        ),
    ]
