# Generated by Django 2.2.6 on 2019-10-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participant',
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='hobby',
            field=models.CharField(blank=True, help_text='半角スペースで単語わけしてください', max_length=255, null=True, verbose_name='趣味'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=None, upload_to='photos', verbose_name='サムネ画像'),
        ),
        migrations.AddField(
            model_name='event',
            name='introduction',
            field=models.TextField(default=None, max_length=2000, verbose_name='紹介'),
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=8),
        ),
        migrations.AddField(
            model_name='event',
            name='leader',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
        ),
        migrations.AddField(
            model_name='event',
            name='member_capacity',
            field=models.IntegerField(default=None),
        ),
    ]
