# Generated by Django 2.2.6 on 2019-10-19 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20191019_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='content',
        ),
    ]
